# Generated by Django 4.1 on 2022-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_user_movie_suggested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_short',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
