# Generated by Django 4.1 on 2022-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_movie_title_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_short',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
