# Generated by Django 4.1 on 2022-08-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_movie_limited_integer_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='limited_integer_field',
            new_name='rating',
        ),
    ]
