# Generated by Django 4.1 on 2022-08-08 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_limited_integer_field_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tags',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_short',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_cover',
            field=models.FileField(default='default.jpg', upload_to='user_directory_path'),
        ),
        migrations.AddField(
            model_name='movie',
            name='suggested_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='anonymous', max_length=40)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stars', models.IntegerField(choices=[(1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)])),
                ('comment', models.TextField(max_length=4000)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.movie')),
            ],
        ),
    ]
